#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

export TEAMCITY_DATA_PATH=${OPENSHIFT_DATA_DIR}
export TEAMCITY_SERVER_MEM_OPTS=-Xmx512m -XX:MaxPermSize=270m

INSTALL_DIR=${OPENSHIFT_HOMEDIR}app-root/runtime

echo "Starting teamcity."
nohup ${INSTALL_DIR}/TeamCity/bin/runAll.sh start -p ${INSTALL_DIR}/teamcity/run/teamcity.pid
